### ISSUE TITLE
Include documentation for operation

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet_ops#1]
We wish to develop a self-documenting set of operations.  This documentation will be presented to the user in the Operations Browser, and in auto-generated documentation.

Could you add a compulsory schema element that can contain HTML text?  Then insert a bit of placeholder text for each one.

**Comment by dinkoivanov** [comment]
I did some research and it looks like CDATA type is not allowed in exsd. It's not mentioned in the limitations here http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Ftools%2Feditors%2Fschema_editor%2Feditor.htm, however if I manually edit the exsd file and change the description element type to CDATA, then the plugin.xml editor breaks when I enter HTML in the description element.
I guess we can either provide documentation as plain text (perhaps in conjunction with wikimarkup - https://en.wikipedia.org/wiki/Wiki_markup), or use an attribute of type "resource" which can point to an HTML file holding the documentation.
What do you think? I also asked the community here: https://www.eclipse.org/forums/index.php/t/1074436/, but I'm not very optimistic.

**Comment by IanMayo** [comment]
ok, let's wait & see the responses.

An Ascii Markup (like wiki markup) would be an acceptable workaround.

**Comment by IanMayo** [comment]
On 28th Feb Dinko said "Can be closed".

@dinkoivanov - could you include a link to committed code that demonstrates this, just to keep things tidy & traceable?

**Comment by dinkoivanov** [comment]
Documentation element added with commit 7ee0b0407c4e18b9ef528133b9251c2a21c46b31. Sample documentation elements provided for all the operations. To go forward I think we can use the Mylyn/WikiText project (https://wiki.eclipse.org/Mylyn/WikiText) to handle parsing & presenting operation documentation. Here is a link that recommends it as a good java library to handle WikiText: https://blog.makk.es/java-libs-for-processing-wiki-markup.html

**Comment by dinkoivanov** [comment]
I did another try with HTML and it actually worked. I'm not sure how I got deceived in my initial research from Feb 3rd. 
Without any change to the schema, I was able to enter HTML tags in the documentation field, those were encoded in the plugin.xml editor and on runtime I was able to get the unencoded documentation content, i.e. the actual HTML tags. Check the attached image:
![html](https://cloud.githubusercontent.com/assets/4459598/13549639/a015ed8e-e312-11e5-985c-582513bf620c.png)
So with this commit: 17f27072f109fd1618dfa03c57f05d8a47f8ceef I removed the comment that WikiText is supported (wrote HTML is supported instead). Could you give it a try on your end as well?

**Comment by IanMayo** [comment]
Yes, this works fine.
