### ISSUE TITLE
Introduce collection data-type

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet_ops#13]
In Limpet, most of the data model objects we'll be working with will be collections/series of data items.

So, in this tech demonstrator, could you introduce a couple of arrays as our model objects.  We can then develop tests that are only applicable if the selections are both arrays/collections, and if they are of equal length.

I suggest these sample entities:
- [1, 2, 3, 4, 5]
- [2, 3, 4, 5, 6]
- [1, 2, 3]
- ["a", "b", "c", "d", "e"]

With these present, then "add" and "subtract" could apply when the first two are selected (since they contain the same number of elements).  "Mean" could apply if one of the first three are selected.  "Concatenate" if the list of strings is selected.

To add to the complexity, many of our data structures will be time series, so we could do with some kind of "couplet" entites that allow a value and a timestamp to be stored, such as:
- [ [0, 1.1], [1000, 2.2], [2000, 4.5], [3000, 3.0], [4000, 6.0] ]
- [ [0, 2.1], [1000, 3.2], [2000, 1.5], [3000, 1.0], [4000, 2.0] ]
- [ [0, 3.1], [3000, 2.0], [4000, 1.0] ]
- [ [0, 0.1], [1000, 4.2], [2000, 2.5], [3000, 2.0], [5000, 1.0] ]
- [ [0, 4.1], [1000, 1.2], [2000, 3.5], [3000, 4.0], [4000, 3.0], [5000, 6.0 ] ]

With these present, we could allow "add" for the first two - since they are at the same time stamps.  

We could alternatively allow "Add (indexed from 1)", "Add (indexed from 2)", "Add (indexed from 3)" and "Add (indexed from 4) if 1&2&3&4 are selected.  When the first one is selected, we will produce values to sum in the other series by interpolating the value at each timestamp in series 1.

**Comment by dinkoivanov** [comment]
Clear, at first glance I think that with the current design "Add" and "Add Indexed" should be two different operations, since "Add Indexed" will define an inputPermutator. In terms of User Experience, the effect in the operations browser will be that user will see two nodes "Add" and "Add Indexed". The first will be disabled when time series 1,2 and 3 above are selected for example. Would that be acceptable?

**Comment by IanMayo** [comment]
Yes, two items is acceptable.
