### ISSUE TITLE
Support libraries of operations

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet_ops#4]
As the library of operations grows, we wish to store operations in subject-specific libraries, and let users switch on/off the libraries in use.

Hmm, this may be overkill, but I think we should support libraries in a similar way to Eclipse Views/Categories. 

So, a library gets defined once.  Then in assorted plugins, we we define an operation we can specify which library it fits into.  This will allow libraries to be defined across multiple plugins, and for plugins to contribute operations to libraries defined in other plugins.

The library should have a documentation element, that describes the purpose/content of that library.

We will provide a Preferences page that allows a user to activate/de-activate libraries.

Our Operations Browser ( #2 ) will show a tree of operations, grouped according to the library.  Selecting a library in a the list of operations will show the documentation for that library in the detail view.

**Comment by dinkoivanov** [comment]
Could you give an example of few libraries with corresponding operations? What will be the business/user value of a library? Could it be a "category" string instead, giving the option one operation to belong to multiple categories? I would imagine that a plugin declaring a library, will also declare the operations for that library. How about the situation when a plugin tries to contribute an operation to an undefined library? Or if two plugins try to declare the same library?

**Comment by IanMayo** [comment]
I guess examples of categories could be "core", "acoustics" and "statistics". A niche group of users may require their own statistics operations, to be presented in the main " statistics " group.

**Comment by IanMayo** [comment]
The benefit of categories is that they can be used to refine what is available: to make it easier to find relevant operations, and keep the size/complexity of the right click pop-up menu down. We may ultimately also have a performance problem when checking if the current selection is applicable to a large range of operations- particularly if the "applies to" test gets expensive.

**Comment by IanMayo** [comment]
```
  Two plugins try to declare the same library?
```

Hmm, do you know how Eclipse handles it, when two menu contribution points are defined with the same ID?  I don't know if Eclipse fails gracefully or not, but it _could_ be an interesting precedent for us to follow.

**Comment by dinkoivanov** [comment]
I checked for view categories, seems like only the first one is considered, next is ignored. No errors, I think plugin bundle resolution order determines which category is first.

**Comment by IanMayo** [comment]
ok. I'm happy with a similar strategy for if we get two libraries with the same id.  Only the first one is recognised, and all operations that refer to that id get added to that first one.

**Comment by IanMayo** [comment]
On 28th Feb Dinko said:

```
I can extend the Schema to support definition of libraries and also the 
context menu building to handle 1 more level of submenus w.r.t. libraries.
```

Yes please - one more level of submenus for libraries.

**Comment by dinkoivanov** [comment]
The schema has been extended. Besides operation, developers now can also add libraries using the same extension point. A library is defined by its ID and name. In addition parent library ID can be specified to support hierarchies of libraries. A library should also contain a documentation element just like operations. When operation is defined, optional library ID might be supplied. When presenting operations in a menu, nesting is done according to library ID. Library hierarchy is also taken in account. If operation is missing a library, then it's presented at root level. The Applicability JUnit test has also been updated to also assert that operation is created in the proper library menu group.

There are two libraries defined in the sampleModel plugin.xml, one for string and one for arithmetic operations. Different plugins contribute to those libraries. To demonstrate library hierarchies, one library has been defined inside the arithmetic library containing the Distance operation.

Please review when you've got a chance and let me know what you think.

**Comment by IanMayo** [comment]
Done - these categories are working fine.
