### ISSUE TITLE
Unit testing strategy

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet_ops#5]
As you know, our current applicability is defined in code.  We can create our operation classes in JUnit tests, and verify that the operations work as expected.

These tests verify:
- that our compliance tests work deliver the expected results
- that our operations are only offered for suitable selections (i.e. that the compliance tests work)

I can't immediately think how we would perform this testing in a declarative context.

Would we run the JUnit as  an Eclipse Plugin Test?  I guess this could retrieve the operations. We could then retrieve a specific one, and run it?

Or, do we break down our tests into separate blocks of functionality:
- test our high level logic works (currently in SampleView)
- test our applicability tests (properties, support classes)
- test our operations deliver the expected output.

**Comment by dinkoivanov** [comment]
This should be a JUnit plugin test. We'll refactor the current logic in the SampleView, so that the test can compose some selection, then pass it to a method which only retuns applicable operations. The test will (1) assert only specific operations are applicable and (2) actually perform the operation and check the result.

**Comment by IanMayo** [comment]
Ok.  Should we explore this in this repo, or wait until we're back in the main Limpet repo?

**Comment by dinkoivanov** [comment]
I would say in this repo we go through the main challenges and proof the design, then move back to the main repo and do the actual work + unit tests there.

**Comment by IanMayo** [comment]
ok. But, do we prove the test strategy in this repo ?  Or doesn't it carry any risk/challenge?

**Comment by dinkoivanov** [comment]
We can certainly prove it here. I'll create a separate plugin and create some unit tests for the applicability.

**Comment by IanMayo** [comment]
Cool. Good plan.

**Comment by IanMayo** [comment]
Demonstration test provided:
https://github.com/debrief/limpet_ops/blob/master/sampleTest/src/sampletest/TestOperationsApplicability.java
