### ISSUE TITLE
Grouped/categorised operators

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet_ops#7]
This is currently theoretical...

But, as our library of operators grows, I think we should acknowledge that some operators may only relate to specific niches (testing for acoustic data).

It does look like the **namespace** attribute may be a placeholder for this.

**Comment by dinkoivanov** [comment]
Namespaces somehow overlap with the idea of libraries (#4). Is this issue still relevant?

**Comment by IanMayo** [comment]
Hmm yes - I think you're right.  Closing this as duplicate of #4
