### ISSUE TITLE
Strange de-select behaviour

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet_ops#9]
I'm playing with your branch, Mac OSX.

I select two items. such as the first two numbers.  Then I right-click on the second item, to see the list of operations.  After about a second, the first item becomes unselected, so only the second one is selected.

I can't imagine that you would implement this, but would you mind checking to see if it happens under MS Windows?

**Comment by dinkoivanov** [comment]
This does not happen in Windows 8, I can check later with Windows 10 and also Max OSX Yosemite. It might be a bug, does it happen upon right-click in the project explorer?

**Comment by IanMayo** [comment]
Still getting this de-select behaviour.  I don't get it when I multi-select items in the Project Explorer. or in the Eclipse IDE.

**Comment by IanMayo** [comment]
Ok, the problem has gone away (possibly with switch to Linux Mint)
